// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhysicsGame.DAL.Context;

#nullable disable

namespace PhysicsGame.DAL.Migrations
{
    [DbContext(typeof(PhysicsGameContext))]
    partial class PhysicsGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Chemistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChemicalData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chemicalData");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definition");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responseText");

                    b.Property<int>("RightResponse")
                        .HasColumnType("int")
                        .HasColumnName("right_reponse");

                    b.HasKey("Id");

                    b.ToTable("Chemistry");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Connections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("login");

                    b.Property<string>("ScoreChemistry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scoreChemistry");

                    b.Property<string>("ScorePhysics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scorePhysics");

                    b.HasKey("Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Electromagnetism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Identifier")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_en");

                    b.Property<string>("QuestionFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_fr");

                    b.Property<string>("ResponseAEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_en");

                    b.Property<string>("ResponseAFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_fr");

                    b.Property<string>("ResponseBEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_en");

                    b.Property<string>("ResponseBFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_fr");

                    b.Property<string>("ResponseCEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_en");

                    b.Property<string>("ResponseCFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_fr");

                    b.Property<string>("RightResponseEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_en");

                    b.Property<string>("RightResponseFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_fr");

                    b.HasKey("Id");

                    b.ToTable("Electromagnetism");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Feedbacks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedbackText");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("login");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Mechanics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Identifier")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_en");

                    b.Property<string>("QuestionFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_fr");

                    b.Property<string>("ResponseAEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_en");

                    b.Property<string>("ResponseAFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_fr");

                    b.Property<string>("ResponseBEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_en");

                    b.Property<string>("ResponseBFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_fr");

                    b.Property<string>("ResponseCEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_en");

                    b.Property<string>("ResponseCFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_fr");

                    b.Property<string>("RightResponseEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_en");

                    b.Property<string>("RightResponseFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_fr");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.ModernPhysics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Identifier")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_en");

                    b.Property<string>("QuestionFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_fr");

                    b.Property<string>("ResponseAEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_en");

                    b.Property<string>("ResponseAFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_fr");

                    b.Property<string>("ResponseBEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_en");

                    b.Property<string>("ResponseBFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_fr");

                    b.Property<string>("ResponseCEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_en");

                    b.Property<string>("ResponseCFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_fr");

                    b.Property<string>("RightResponseEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_en");

                    b.Property<string>("RightResponseFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_fr");

                    b.HasKey("Id");

                    b.ToTable("ModernPhysics");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Optics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Identifier")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_en");

                    b.Property<string>("QuestionFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_fr");

                    b.Property<string>("ResponseAEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_en");

                    b.Property<string>("ResponseAFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_fr");

                    b.Property<string>("ResponseBEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_en");

                    b.Property<string>("ResponseBFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_fr");

                    b.Property<string>("ResponseCEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_en");

                    b.Property<string>("ResponseCFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_fr");

                    b.Property<string>("RightResponseEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_en");

                    b.Property<string>("RightResponseFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_fr");

                    b.HasKey("Id");

                    b.ToTable("Optics");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Relativity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Identifier")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_en");

                    b.Property<string>("QuestionFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_fr");

                    b.Property<string>("ResponseAEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_en");

                    b.Property<string>("ResponseAFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_fr");

                    b.Property<string>("ResponseBEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_en");

                    b.Property<string>("ResponseBFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_fr");

                    b.Property<string>("ResponseCEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_en");

                    b.Property<string>("ResponseCFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_fr");

                    b.Property<string>("RightResponseEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_en");

                    b.Property<string>("RightResponseFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_fr");

                    b.HasKey("Id");

                    b.ToTable("Relativity");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.Thermodynamics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Identifier")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_en");

                    b.Property<string>("QuestionFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_fr");

                    b.Property<string>("ResponseAEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_en");

                    b.Property<string>("ResponseAFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_A_fr");

                    b.Property<string>("ResponseBEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_en");

                    b.Property<string>("ResponseBFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_B_fr");

                    b.Property<string>("ResponseCEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_en");

                    b.Property<string>("ResponseCFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_C_fr");

                    b.Property<string>("RightResponseEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_en");

                    b.Property<string>("RightResponseFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("right_response_fr");

                    b.HasKey("Id");

                    b.ToTable("Thermodynamics");
                });

            modelBuilder.Entity("PhysicsGame.DAL.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
